<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ligen">
<meta name="dcterms.date" content="2026-03-31">

<title>Take-home Exercise 2 - Prototype Module: Customer Engagement &amp; Experience – VAA_handson_exercise</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-670e21d9272e96e6d83d57d20a7c98fc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">VAA_handson_exercise</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-pencil" role="img">
</i> 
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html">
 <span class="dropdown-text">Hands-on Part 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html">
 <span class="dropdown-text">Hands-on Part 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html">
 <span class="dropdown-text">Hands-on Part 3a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html">
 <span class="dropdown-text">Hands-on Part 3b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.html">
 <span class="dropdown-text">Hands-on Part 4a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html">
 <span class="dropdown-text">Hands-on Part 4b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.html">
 <span class="dropdown-text">Hands-on Part 4c</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.html">
 <span class="dropdown-text">Hands-on Part 4d</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html">
 <span class="dropdown-text">Hands-on Part 5a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html">
 <span class="dropdown-text">Hands-on Part 5b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05c.html">
 <span class="dropdown-text">Hands-on Part 5c</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05d.html">
 <span class="dropdown-text">Hands-on Part 5d</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05e.html">
 <span class="dropdown-text">Hands-on Part 5e</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html">
 <span class="dropdown-text">Hands-on Part 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08a.html">
 <span class="dropdown-text">Hands-on Part 8a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08b.html">
 <span class="dropdown-text">Hands-on Part 8b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08c.html">
 <span class="dropdown-text">Hands-on Part 8c</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html">
 <span class="dropdown-text">Hands-on Part 9</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html">
 <span class="dropdown-text">Hands-on Part 10</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-backpack" role="img">
</i> 
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://elliolee.github.io/ISSS608_VAA_ColombianFintech-project-website/"> <i class="bi bi-people" role="img">
</i> 
<span class="menu-text">Group Project</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">1 Introduction</a>
  <ul class="collapse">
  <li><a href="#project-background" id="toc-project-background" class="nav-link" data-scroll-target="#project-background">1.1 Project Background</a></li>
  <li><a href="#module-2-objective" id="toc-module-2-objective" class="nav-link" data-scroll-target="#module-2-objective">1.2 Module 2 Objective</a></li>
  </ul></li>
  <li><a href="#proposed-project-storyline" id="toc-proposed-project-storyline" class="nav-link" data-scroll-target="#proposed-project-storyline">2 Proposed Project Storyline</a>
  <ul class="collapse">
  <li><a href="#overall-project-storyline" id="toc-overall-project-storyline" class="nav-link" data-scroll-target="#overall-project-storyline">2.1 Overall Project Storyline</a></li>
  <li><a href="#role-of-module-2-in-the-larger-system" id="toc-role-of-module-2-in-the-larger-system" class="nav-link" data-scroll-target="#role-of-module-2-in-the-larger-system">2.2 Role of Module 2 in the Larger System</a></li>
  </ul></li>
  <li><a href="#data-preparation-process" id="toc-data-preparation-process" class="nav-link" data-scroll-target="#data-preparation-process">3 Data Preparation Process</a>
  <ul class="collapse">
  <li><a href="#required-r-packages" id="toc-required-r-packages" class="nav-link" data-scroll-target="#required-r-packages">3.1 Required R Packages</a></li>
  <li><a href="#import-and-inspect-the-dataset" id="toc-import-and-inspect-the-dataset" class="nav-link" data-scroll-target="#import-and-inspect-the-dataset">3.2 Import and Inspect the Dataset</a></li>
  <li><a href="#variable-grouping-for-module-2" id="toc-variable-grouping-for-module-2" class="nav-link" data-scroll-target="#variable-grouping-for-module-2">3.3 Variable Grouping for Module 2</a></li>
  <li><a href="#data-cleaning-and-transformation" id="toc-data-cleaning-and-transformation" class="nav-link" data-scroll-target="#data-cleaning-and-transformation">3.4 Data Cleaning and Transformation</a></li>
  <li><a href="#validation-of-key-variables" id="toc-validation-of-key-variables" class="nav-link" data-scroll-target="#validation-of-key-variables">3.5 Validation of Key Variables</a></li>
  </ul></li>
  <li><a href="#selection-of-visualisation-techniques" id="toc-selection-of-visualisation-techniques" class="nav-link" data-scroll-target="#selection-of-visualisation-techniques">4 Selection of Visualisation Techniques</a>
  <ul class="collapse">
  <li><a href="#average-feature-usage-diversity-by-product-ownership" id="toc-average-feature-usage-diversity-by-product-ownership" class="nav-link" data-scroll-target="#average-feature-usage-diversity-by-product-ownership">4.1 Average Feature Usage Diversity by Product Ownership</a></li>
  <li><a href="#average-app-login-frequency-by-product-ownership" id="toc-average-app-login-frequency-by-product-ownership" class="nav-link" data-scroll-target="#average-app-login-frequency-by-product-ownership">4.2 Average App Login Frequency by Product Ownership</a></li>
  <li><a href="#nps-score-by-satisfaction-score" id="toc-nps-score-by-satisfaction-score" class="nav-link" data-scroll-target="#nps-score-by-satisfaction-score">4.3 NPS Score by Satisfaction Score</a></li>
  <li><a href="#nps-score-by-feature-usage-diversity-bucket" id="toc-nps-score-by-feature-usage-diversity-bucket" class="nav-link" data-scroll-target="#nps-score-by-feature-usage-diversity-bucket">4.4 NPS Score by Feature Usage Diversity Bucket</a></li>
  <li><a href="#complaint-topics-distribution" id="toc-complaint-topics-distribution" class="nav-link" data-scroll-target="#complaint-topics-distribution">4.5 Complaint Topics Distribution</a></li>
  <li><a href="#nps-score-by-support-ticket-bucket" id="toc-nps-score-by-support-ticket-bucket" class="nav-link" data-scroll-target="#nps-score-by-support-ticket-bucket">4.6 NPS Score by Support Ticket Bucket</a></li>
  </ul></li>
  <li><a href="#visualisation-design-and-interaction-principles" id="toc-visualisation-design-and-interaction-principles" class="nav-link" data-scroll-target="#visualisation-design-and-interaction-principles">5 Visualisation Design and Interaction Principles</a>
  <ul class="collapse">
  <li><a href="#readability-and-comparability" id="toc-readability-and-comparability" class="nav-link" data-scroll-target="#readability-and-comparability">5.1 Readability and Comparability</a></li>
  <li><a href="#progressive-diagnostic-flow" id="toc-progressive-diagnostic-flow" class="nav-link" data-scroll-target="#progressive-diagnostic-flow">5.2 Progressive Diagnostic Flow</a></li>
  <li><a href="#chart-type-suitability" id="toc-chart-type-suitability" class="nav-link" data-scroll-target="#chart-type-suitability">5.3 Chart-Type Suitability</a></li>
  <li><a href="#coordinated-views-for-future-shiny-use" id="toc-coordinated-views-for-future-shiny-use" class="nav-link" data-scroll-target="#coordinated-views-for-future-shiny-use">5.4 Coordinated Views for Future Shiny Use</a></li>
  </ul></li>
  <li><a href="#proposed-ui-design" id="toc-proposed-ui-design" class="nav-link" data-scroll-target="#proposed-ui-design">6 Proposed UI Design</a>
  <ul class="collapse">
  <li><a href="#proposed-inputs" id="toc-proposed-inputs" class="nav-link" data-scroll-target="#proposed-inputs">6.1 Proposed Inputs</a></li>
  <li><a href="#proposed-outputs" id="toc-proposed-outputs" class="nav-link" data-scroll-target="#proposed-outputs">6.2 Proposed Outputs</a></li>
  <li><a href="#proposed-ui-components-and-layout" id="toc-proposed-ui-components-and-layout" class="nav-link" data-scroll-target="#proposed-ui-components-and-layout">6.3 Proposed UI Components and Layout</a></li>
  <li><a href="#early-ui-storyboard-sketch" id="toc-early-ui-storyboard-sketch" class="nav-link" data-scroll-target="#early-ui-storyboard-sketch">6.4 Early UI Storyboard Sketch</a></li>
  </ul></li>
  <li><a href="#prototype-visualisations" id="toc-prototype-visualisations" class="nav-link" data-scroll-target="#prototype-visualisations">7 Prototype Visualisations</a>
  <ul class="collapse">
  <li><a href="#average-feature-usage-diversity-by-product-ownership-1" id="toc-average-feature-usage-diversity-by-product-ownership-1" class="nav-link" data-scroll-target="#average-feature-usage-diversity-by-product-ownership-1">7.1 Average Feature Usage Diversity by Product Ownership</a></li>
  <li><a href="#average-app-login-frequency-by-product-ownership-1" id="toc-average-app-login-frequency-by-product-ownership-1" class="nav-link" data-scroll-target="#average-app-login-frequency-by-product-ownership-1">7.2 Average App Login Frequency by Product Ownership</a></li>
  <li><a href="#nps-score-by-satisfaction-score-1" id="toc-nps-score-by-satisfaction-score-1" class="nav-link" data-scroll-target="#nps-score-by-satisfaction-score-1">7.3 NPS Score by Satisfaction Score</a></li>
  <li><a href="#nps-score-by-feature-usage-diversity-bucket-1" id="toc-nps-score-by-feature-usage-diversity-bucket-1" class="nav-link" data-scroll-target="#nps-score-by-feature-usage-diversity-bucket-1">7.4 NPS Score by Feature Usage Diversity Bucket</a></li>
  <li><a href="#complaint-topics-distribution-excluding-none" id="toc-complaint-topics-distribution-excluding-none" class="nav-link" data-scroll-target="#complaint-topics-distribution-excluding-none">7.5 Complaint Topics Distribution (Excluding “None”)</a></li>
  <li><a href="#nps-score-by-support-ticket-bucket-1" id="toc-nps-score-by-support-ticket-bucket-1" class="nav-link" data-scroll-target="#nps-score-by-support-ticket-bucket-1">7.6 NPS Score by Support Ticket Bucket</a></li>
  <li><a href="#prototype-kpi-summary" id="toc-prototype-kpi-summary" class="nav-link" data-scroll-target="#prototype-kpi-summary">7.7 Prototype KPI Summary</a></li>
  <li><a href="#product-level-engagement-summary" id="toc-product-level-engagement-summary" class="nav-link" data-scroll-target="#product-level-engagement-summary">7.8 Product-level Engagement Summary</a></li>
  <li><a href="#product-level-login-summary" id="toc-product-level-login-summary" class="nav-link" data-scroll-target="#product-level-login-summary">7.9 Product-level Login Summary</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">8 Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 2 - Prototype Module: Customer Engagement &amp; Experience</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ligen </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 31, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">March 31, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>1 Introduction</h1>
<section id="project-background" class="level2">
<h2 class="anchored" data-anchor-id="project-background">1.1 Project Background</h2>
<p>Fintech platforms generate large volumes of customer-level data related to product adoption, digital engagement, transaction behaviour, service experience, and retention outcomes. While customer structure and product ownership patterns are important starting points, fintech product and CRM teams also need to understand how customers actually interact with the platform and how they evaluate the service experience they receive.</p>
<p>This project develops a visual analytics dashboard for the COFINFAD Colombian fintech customer dataset. The proposed system is designed as a web-enabled Shiny application that supports interactive exploration and data-driven decision-making for business users. Rather than functioning as a collection of isolated charts, the dashboard is structured as a multi-module analytical system that moves progressively from customer overview to engagement and experience, and finally to retention and customer value.</p>
</section>
<section id="module-2-objective" class="level2">
<h2 class="anchored" data-anchor-id="module-2-objective">1.2 Module 2 Objective</h2>
<p>This prototype focuses on <strong>Module 2: Customer Engagement &amp; Experience</strong>. The objective of this module is to analyse how customers interact with the fintech platform and evaluate their service experience.</p>
<p>More specifically, the module examines four connected aspects of customer behaviour and experience:</p>
<ul>
<li>engagement breadth, represented by feature usage diversity and its relationship with product ownership,</li>
<li>engagement intensity, represented by app login frequency across product ownership groups,</li>
<li>experience evaluation, represented by the relationship between satisfaction and NPS,</li>
<li>and service friction, represented by complaint topic distribution and support burden.</li>
</ul>
<p>These perspectives allow the module to move from how customers use the platform, to how they evaluate the service experience, and finally to where operational friction emerges.</p>
</section>
</section>
<section id="proposed-project-storyline" class="level1">
<h1>2 Proposed Project Storyline</h1>
<section id="overall-project-storyline" class="level2">
<h2 class="anchored" data-anchor-id="overall-project-storyline">2.1 Overall Project Storyline</h2>
<p>The proposed Shiny application follows a progressive analytical workflow:</p>
<p><strong>Customer Overview → Customer Engagement &amp; Experience → Customer Retention &amp; Value</strong></p>
<p>This structure allows users to move from understanding who the customers are, to examining how they use the platform and how they experience its services, and finally to identifying high-risk and high-value customer groups.</p>
</section>
<section id="role-of-module-2-in-the-larger-system" class="level2">
<h2 class="anchored" data-anchor-id="role-of-module-2-in-the-larger-system">2.2 Role of Module 2 in the Larger System</h2>
<p>Module 1 provides the structural foundation of the dashboard by analysing customer demographics, acquisition channels, and financial product adoption patterns. Module 3 focuses on customer retention and business value through churn analysis and predictive modelling of Customer Lifetime Value (CLV).</p>
<p>Module 2 sits between these two modules and acts as the behavioural and experience diagnostic layer. It extends Module 1 by examining whether product adoption is associated with broader platform usage and whether interaction patterns translate into customer advocacy. It also supports Module 3 by showing how customer satisfaction, complaints, and support burden may help explain downstream retention and value outcomes. In this way, Module 2 functions as the analytical bridge between customer structure and business outcomes.</p>
</section>
</section>
<section id="data-preparation-process" class="level1">
<h1>3 Data Preparation Process</h1>
<section id="required-r-packages" class="level2">
<h2 class="anchored" data-anchor-id="required-r-packages">3.1 Required R Packages</h2>
<p>The following R packages are used in this prototype module. All of them are supported on CRAN.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  tidyverse,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  ggplot2,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  plotly,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  scales,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  forcats,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  patchwork,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  DT,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  lubridate,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  shiny</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<ul>
<li><code>tidyverse</code> supports data import, wrangling, and transformation.</li>
<li><code>ggplot2</code> is used to generate the prototype visualisations.</li>
<li><code>plotly</code> can be used to convert static plots into interactive views for the future Shiny application.</li>
<li><code>scales</code> helps format percentages and axes.</li>
<li><code>forcats</code> supports categorical variable handling.</li>
<li><code>patchwork</code> is used to combine plots during prototyping if needed.</li>
<li><code>DT</code> supports interactive tables.</li>
<li><code>lubridate</code> is used for date parsing and transformation.</li>
<li><code>shiny</code> will be used later to implement the final interactive module.</li>
</ul>
<p>These packages support data cleaning, categorical handling, grouped summaries, and the construction of prototype visualisations for engagement, experience, and service friction analysis. Some packages such as plotly, DT, and patchwork are included to support potential interactive extension, tabular display, and layout composition in the future Shiny implementation.</p>
</section>
<section id="import-and-inspect-the-dataset" class="level2">
<h2 class="anchored" data-anchor-id="import-and-inspect-the-dataset">3.2 Import and Inspect the Dataset</h2>
<p>The code chunk below is used to read the customer-level dataset into R.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>customer_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/customer_data.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The code chunk below is used to inspect the size, structure, and variable names of the dataset.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(customer_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 48723    57</code></pre>
</div>
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(customer_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 48,723
Columns: 57
$ customer_id                &lt;dbl&gt; 93716481, 49020929, 52690950, 23199751, 619…
$ age                        &lt;dbl&gt; 44, 44, 45, 45, 44, 45, 44, 44, 45, 44, 44,…
$ gender                     &lt;chr&gt; "Male", "Male", "Male", "Male", "Female", "…
$ city                       &lt;chr&gt; "Pereira", "Cali", "Barranquilla", "Bogota"…
$ department                 &lt;chr&gt; "Risaralda", "Valle del Cauca", "Atlantico"…
$ latitude                   &lt;dbl&gt; 4.785461, 3.410843, 11.010192, 4.653382, 4.…
$ longitude                  &lt;dbl&gt; -75.78832, -76.58121, -74.82318, -74.08363,…
$ income_bracket             &lt;chr&gt; "Very High", "Medium", "High", "High", "Med…
$ occupation                 &lt;chr&gt; "Engineer", "Construction Worker", "Constru…
$ education_level            &lt;chr&gt; "Master", "Bachelor", "Bachelor", "High Sch…
$ marital_status             &lt;chr&gt; "Married", "Married", "Married", "Single", …
$ household_size             &lt;dbl&gt; 5, 2, 4, 2, 3, 4, 4, 3, 1, 3, 5, 3, 3, 7, 3…
$ acquisition_channel        &lt;chr&gt; "Partnership", "Paid Ad", "Paid Ad", "Refer…
$ customer_segment           &lt;chr&gt; "occasional", "regular", "inactive", "inact…
$ savings_account            &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, T…
$ credit_card                &lt;lgl&gt; TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE…
$ personal_loan              &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, F…
$ investment_account         &lt;lgl&gt; FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, FALS…
$ insurance_product          &lt;lgl&gt; TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FAL…
$ active_products            &lt;dbl&gt; 1, 5, 3, 2, 1, 1, 1, 4, 2, 3, 1, 5, 3, 1, 1…
$ app_logins_frequency       &lt;dbl&gt; 15, 30, 4, 15, 19, 15, 44, 22, 7, 11, 7, 30…
$ feature_usage_diversity    &lt;dbl&gt; 3, 0, 4, 4, 1, 4, 6, 1, 1, 6, 3, 1, 2, 1, 3…
$ bill_payment_user          &lt;lgl&gt; FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE,…
$ auto_savings_enabled       &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FA…
$ credit_utilization_ratio   &lt;dbl&gt; 0.17871029, NA, NA, NA, 0.40360553, 0.07786…
$ international_transactions &lt;dbl&gt; 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0…
$ failed_transactions        &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0…
$ tx_count                   &lt;dbl&gt; 76, 10, 10, 23, 18, 15, 24, 45, 134, 13, 18…
$ avg_tx_value               &lt;dbl&gt; 1679872.4, 5445810.0, 640335.0, 660180.4, 1…
$ total_tx_volume            &lt;dbl&gt; 127670300, 54458100, 6403350, 15184150, 262…
$ first_tx                   &lt;chr&gt; "1/5/23", "2/5/23", "1/31/23", "1/10/23", "…
$ last_tx                    &lt;chr&gt; "12/25/23", "12/20/23", "12/12/23", "12/24/…
$ base_satisfaction          &lt;dbl&gt; 9.213372, 6.073093, 8.198643, 7.529577, 6.6…
$ tx_satisfaction            &lt;dbl&gt; 0.380, 0.050, 0.050, 0.115, 0.090, 0.075, 0…
$ product_satisfaction       &lt;dbl&gt; 0.6, 0.2, 0.6, 0.4, 0.4, 0.6, 0.4, 0.4, 0.6…
$ satisfaction_score         &lt;dbl&gt; 5, 3, 4, 4, 3, 4, 4, 4, 5, 4, 4, 5, 4, 3, 4…
$ nps_score                  &lt;dbl&gt; -7, -46, -29, -31, -47, -29, -34, -36, -4, …
$ last_survey_date           &lt;chr&gt; "12/16/23", "5/5/23", "11/16/23", "5/7/23",…
$ support_tickets_count      &lt;dbl&gt; 1, 1, 0, 2, 2, 1, 1, 0, 2, 0, 0, 2, 3, 1, 0…
$ resolved_tickets_ratio     &lt;dbl&gt; 0.0000000, 1.0000000, 0.0000000, 0.5000000,…
$ app_store_rating           &lt;dbl&gt; 3.5, 4.0, 5.0, 4.5, 4.0, 4.0, 5.0, 4.5, 4.5…
$ feedback_sentiment         &lt;chr&gt; "Neutral", "Positive", "Positive", "Positiv…
$ feature_requests           &lt;chr&gt; "Budgeting tools", NA, NA, "Cryptocurrency …
$ complaint_topics           &lt;chr&gt; NA, NA, NA, NA, "App performance", NA, NA, …
$ clv_segment                &lt;chr&gt; "Gold", "Bronze", "Gold", "Bronze", "Gold",…
$ monthly_transaction_count  &lt;dbl&gt; 1.428571, 1.571429, 2.500000, 1.555556, 2.1…
$ average_transaction_value  &lt;dbl&gt; 6054025.0, 2127413.6, 3575915.0, 1513353.6,…
$ total_transaction_volume   &lt;dbl&gt; 60540250, 23401550, 35759150, 21186950, 116…
$ transaction_frequency      &lt;dbl&gt; 0.03076923, 0.03293413, 0.05000000, 0.04778…
$ last_transaction_date      &lt;chr&gt; "12/5/23", "12/18/23", "10/27/23", "11/30/2…
$ preferred_transaction_type &lt;chr&gt; "Transfer", "Transfer", "Transfer", "Transf…
$ first_transaction_date     &lt;chr&gt; "1/5/23", "2/5/23", "1/31/23", "1/10/23", "…
$ weekend_transaction_ratio  &lt;dbl&gt; 0.30000000, 0.18181818, 0.30000000, 0.14285…
$ avg_daily_transactions     &lt;dbl&gt; 0.03076923, 0.03293413, 0.05000000, 0.04778…
$ customer_tenure            &lt;dbl&gt; 11.633333, 11.500000, 8.766667, 10.733333, …
$ churn_probability          &lt;dbl&gt; 0.3622688, 0.1817896, 0.3212651, 0.3366287,…
$ customer_lifetime_value    &lt;dbl&gt; 312414808, 167022286, 19403711, 35978105, 3…</code></pre>
</div>
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(customer_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "customer_id"                "age"                       
 [3] "gender"                     "city"                      
 [5] "department"                 "latitude"                  
 [7] "longitude"                  "income_bracket"            
 [9] "occupation"                 "education_level"           
[11] "marital_status"             "household_size"            
[13] "acquisition_channel"        "customer_segment"          
[15] "savings_account"            "credit_card"               
[17] "personal_loan"              "investment_account"        
[19] "insurance_product"          "active_products"           
[21] "app_logins_frequency"       "feature_usage_diversity"   
[23] "bill_payment_user"          "auto_savings_enabled"      
[25] "credit_utilization_ratio"   "international_transactions"
[27] "failed_transactions"        "tx_count"                  
[29] "avg_tx_value"               "total_tx_volume"           
[31] "first_tx"                   "last_tx"                   
[33] "base_satisfaction"          "tx_satisfaction"           
[35] "product_satisfaction"       "satisfaction_score"        
[37] "nps_score"                  "last_survey_date"          
[39] "support_tickets_count"      "resolved_tickets_ratio"    
[41] "app_store_rating"           "feedback_sentiment"        
[43] "feature_requests"           "complaint_topics"          
[45] "clv_segment"                "monthly_transaction_count" 
[47] "average_transaction_value"  "total_transaction_volume"  
[49] "transaction_frequency"      "last_transaction_date"     
[51] "preferred_transaction_type" "first_transaction_date"    
[53] "weekend_transaction_ratio"  "avg_daily_transactions"    
[55] "customer_tenure"            "churn_probability"         
[57] "customer_lifetime_value"   </code></pre>
</div>
</div>
<p>The prototype uses the customer-level dataset from COFINFAD. The separate transaction-level dataset is not used in this prototype because the customer-level table already contains sufficient aggregated behavioural and experience variables for Module 2 analysis.</p>
</section>
<section id="variable-grouping-for-module-2" class="level2">
<h2 class="anchored" data-anchor-id="variable-grouping-for-module-2">3.3 Variable Grouping for Module 2</h2>
<p>For this module, the variables are grouped into three analytical categories.</p>
<p><strong>Engagement variables</strong> - <code>feature_usage_diversity</code> - <code>app_logins_frequency</code> - <code>bill_payment_user</code> - <code>auto_savings_enabled</code> - product ownership variables such as <code>savings_account</code>, <code>credit_card</code>, <code>personal_loan</code>, <code>investment_account</code>, and <code>insurance_product</code></p>
<p><strong>Experience evaluation variables</strong> - <code>satisfaction_score</code> - <code>nps_score</code> - <code>app_store_rating</code> - <code>base_satisfaction</code> - <code>tx_satisfaction</code> - <code>product_satisfaction</code></p>
<p><strong>Service friction variables</strong> - <code>complaint_topics</code> - <code>support_tickets_count</code> - <code>feedback_sentiment</code> - <code>resolved_tickets_ratio</code></p>
<p>These grouped variables support the analysis of how customers use the platform, how they evaluate their experience, and where service friction emerges.</p>
</section>
<section id="data-cleaning-and-transformation" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning-and-transformation">3.4 Data Cleaning and Transformation</h2>
<p>The code chunk below prepares the variables required for customer engagement and experience analysis.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>customer_m2 <span class="ot">&lt;-</span> customer_data <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">last_survey_date =</span> lubridate<span class="sc">::</span><span class="fu">ymd</span>(last_survey_date),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">customer_segment =</span> <span class="fu">factor</span>(</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>      customer_segment,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"inactive"</span>, <span class="st">"occasional"</span>, <span class="st">"regular"</span>, <span class="st">"power"</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">acquisition_channel =</span> <span class="fu">as.factor</span>(acquisition_channel),</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">feedback_sentiment =</span> <span class="fu">factor</span>(</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>      feedback_sentiment,</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Negative"</span>, <span class="st">"Neutral"</span>, <span class="st">"Positive"</span>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">complaint_topics =</span> <span class="fu">if_else</span>(</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>      <span class="fu">is.na</span>(complaint_topics),</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>      <span class="st">"None"</span>,</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>      complaint_topics</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">complaint_topics =</span> <span class="fu">as.factor</span>(complaint_topics),</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">support_ticket_bucket =</span> <span class="fu">case_when</span>(</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>      support_tickets_count <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"0"</span>,</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>      support_tickets_count <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"1"</span>,</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>      support_tickets_count <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">"2"</span>,</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>      support_tickets_count <span class="sc">&gt;=</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">"3+"</span>,</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">support_ticket_bucket =</span> <span class="fu">factor</span>(</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>      support_ticket_bucket,</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3+"</span>)</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">feature_usage_bucket =</span> <span class="fu">case_when</span>(</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>      feature_usage_diversity <span class="sc">&lt;=</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"0-1"</span>,</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>      feature_usage_diversity <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">"2"</span>,</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>      feature_usage_diversity <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">"3"</span>,</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>      feature_usage_diversity <span class="sc">&gt;=</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"4+"</span>,</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span></span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">feature_usage_bucket =</span> <span class="fu">factor</span>(</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>      feature_usage_bucket,</span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0-1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span>, <span class="st">"4+"</span>)</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The shared project-level cleaning logic also includes auditing duplicate or overlapping fields, validating range consistency, and checking cross-field consistency. In this module, special attention is given to complaint-related missing values because they directly affect the interpretation of service issue patterns. In addition, support ticket counts and feature usage diversity are grouped into diagnostic buckets to support clearer comparison in the prototype visualisations.</p>
</section>
<section id="validation-of-key-variables" class="level2">
<h2 class="anchored" data-anchor-id="validation-of-key-variables">3.5 Validation of Key Variables</h2>
<p>The code chunk below is used to inspect summary statistics for the main variables used in this module.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>customer_m2 <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    feature_usage_diversity,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    support_tickets_count,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    satisfaction_score,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    nps_score,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    resolved_tickets_ratio,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    app_store_rating</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> feature_usage_diversity support_tickets_count satisfaction_score
 Min.   : 0.00           Min.   :0.0000        Min.   :2.000     
 1st Qu.: 1.00           1st Qu.:0.0000        1st Qu.:4.000     
 Median : 2.00           Median :1.0000        Median :4.000     
 Mean   : 2.37           Mean   :0.9975        Mean   :4.162     
 3rd Qu.: 4.00           3rd Qu.:2.0000        3rd Qu.:5.000     
 Max.   :10.00           Max.   :7.0000        Max.   :6.000     
   nps_score      resolved_tickets_ratio app_store_rating
 Min.   :-80.00   Min.   :0.0000         Min.   :2.000   
 1st Qu.:-34.00   1st Qu.:0.0000         1st Qu.:4.000   
 Median :-28.00   Median :0.5000         Median :4.000   
 Mean   :-26.76   Mean   :0.5062         Mean   :4.156   
 3rd Qu.:-19.00   3rd Qu.:1.0000         3rd Qu.:4.500   
 Max.   : 23.00   Max.   :1.0000         Max.   :5.000   </code></pre>
</div>
</div>
<p>The code chunk below is used to inspect the distributions of selected categorical variables.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>customer_m2 <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(feedback_sentiment, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  feedback_sentiment     n
  &lt;fct&gt;              &lt;int&gt;
1 Positive           38897
2 Neutral             8346
3 Negative            1480</code></pre>
</div>
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>customer_m2 <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(complaint_topics, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  complaint_topics       n
  &lt;fct&gt;              &lt;int&gt;
1 None               24346
2 Customer service    4940
3 Fees                4911
4 Transaction issues  4867
5 Account security    4841
6 App performance     4818</code></pre>
</div>
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>customer_m2 <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(support_ticket_bucket, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  support_ticket_bucket     n
  &lt;fct&gt;                 &lt;int&gt;
1 1                     18071
2 0                     17914
3 2                      8823
4 3+                     3915</code></pre>
</div>
</div>
<p>The code chunk below is used to check the ranges of selected numeric variables.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>customer_m2 <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_feature_diversity =</span> <span class="fu">min</span>(feature_usage_diversity, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_feature_diversity =</span> <span class="fu">max</span>(feature_usage_diversity, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_tickets =</span> <span class="fu">min</span>(support_tickets_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_tickets =</span> <span class="fu">max</span>(support_tickets_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_sat =</span> <span class="fu">min</span>(satisfaction_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_sat =</span> <span class="fu">max</span>(satisfaction_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">min_nps =</span> <span class="fu">min</span>(nps_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">max_nps =</span> <span class="fu">max</span>(nps_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  min_feature_diversity max_feature_diversity min_tickets max_tickets min_sat
                  &lt;dbl&gt;                 &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt;
1                     0                    10           0           7       2
# ℹ 3 more variables: max_sat &lt;dbl&gt;, min_nps &lt;dbl&gt;, max_nps &lt;dbl&gt;</code></pre>
</div>
</div>
<p>These checks help ensure that the selected variables are suitable for prototype visualisation and that the key engagement, experience, and service friction indicators are in usable ranges for grouped comparison.</p>
</section>
</section>
<section id="selection-of-visualisation-techniques" class="level1">
<h1>4 Selection of Visualisation Techniques</h1>
<section id="average-feature-usage-diversity-by-product-ownership" class="level2">
<h2 class="anchored" data-anchor-id="average-feature-usage-diversity-by-product-ownership">4.1 Average Feature Usage Diversity by Product Ownership</h2>
<p>A grouped bar chart is used to compare average feature usage diversity across product ownership conditions. This chart is suitable because product ownership is a binary status, and the objective is to compare average engagement breadth between customers who own and do not own each product type.</p>
</section>
<section id="average-app-login-frequency-by-product-ownership" class="level2">
<h2 class="anchored" data-anchor-id="average-app-login-frequency-by-product-ownership">4.2 Average App Login Frequency by Product Ownership</h2>
<p>A grouped bar chart is used to compare average app login frequency across product ownership conditions. This chart extends the engagement analysis from usage breadth to usage intensity and helps evaluate whether customers who own different financial products also log into the platform more frequently.</p>
</section>
<section id="nps-score-by-satisfaction-score" class="level2">
<h2 class="anchored" data-anchor-id="nps-score-by-satisfaction-score">4.3 NPS Score by Satisfaction Score</h2>
<p>A boxplot is used to compare NPS score distributions across satisfaction score levels. This is appropriate because <code>nps_score</code> is a continuous outcome variable, while <code>satisfaction_score</code> is a discrete rating category. The chart evaluates whether higher satisfaction translates into stronger customer advocacy.</p>
</section>
<section id="nps-score-by-feature-usage-diversity-bucket" class="level2">
<h2 class="anchored" data-anchor-id="nps-score-by-feature-usage-diversity-bucket">4.4 NPS Score by Feature Usage Diversity Bucket</h2>
<p>A boxplot is used to compare NPS score distributions across grouped feature usage levels. This chart provides a direct bridge between platform interaction and service experience by showing whether broader platform usage is associated with stronger customer advocacy.</p>
</section>
<section id="complaint-topics-distribution" class="level2">
<h2 class="anchored" data-anchor-id="complaint-topics-distribution">4.5 Complaint Topics Distribution</h2>
<p>A bar chart is used to visualise complaint topic frequencies because complaint topics are categorical issue types. By excluding customers without recorded complaints, the chart focuses on the actual composition of service issues.</p>
</section>
<section id="nps-score-by-support-ticket-bucket" class="level2">
<h2 class="anchored" data-anchor-id="nps-score-by-support-ticket-bucket">4.6 NPS Score by Support Ticket Bucket</h2>
<p>A boxplot is used to compare NPS score distributions across grouped support ticket levels. Grouping support burden into buckets improves interpretability and helps assess whether heavier service burden is associated with weaker customer advocacy.</p>
</section>
</section>
<section id="visualisation-design-and-interaction-principles" class="level1">
<h1>5 Visualisation Design and Interaction Principles</h1>
<section id="readability-and-comparability" class="level2">
<h2 class="anchored" data-anchor-id="readability-and-comparability">5.1 Readability and Comparability</h2>
<p>The prototype prioritises simple chart forms, clear axis labels, and limited visual clutter. Grouped bar charts are used where average comparisons are needed, while boxplots are used to compare distributions across discrete categories. This supports readability and makes the interpretation of behavioural and experience differences more straightforward.</p>
</section>
<section id="progressive-diagnostic-flow" class="level2">
<h2 class="anchored" data-anchor-id="progressive-diagnostic-flow">5.2 Progressive Diagnostic Flow</h2>
<p>The visualisations are organised into a progressive diagnostic sequence:</p>
<ul>
<li>product ownership and platform usage,</li>
<li>usage and experience relationships,</li>
<li>and service friction.</li>
</ul>
<p>This flow reflects the objective of the module by moving from how customers interact with the platform, to how they evaluate the service experience, and finally to where operational friction may emerge.</p>
</section>
<section id="chart-type-suitability" class="level2">
<h2 class="anchored" data-anchor-id="chart-type-suitability">5.3 Chart-Type Suitability</h2>
<p>Chart types are selected according to variable structure and analytical purpose. Grouped bar charts are used for average comparisons under binary product ownership conditions. Boxplots are used for grouped comparisons involving NPS distributions. Bar charts are used for complaint frequencies because they clearly display issue composition across categories.</p>
</section>
<section id="coordinated-views-for-future-shiny-use" class="level2">
<h2 class="anchored" data-anchor-id="coordinated-views-for-future-shiny-use">5.4 Coordinated Views for Future Shiny Use</h2>
<p>Although this prototype is not yet a full Shiny application, the visualisations are designed to support future coordinated filtering and drill-down. Users will later be able to explore how engagement and experience vary across product ownership groups, customer segments, acquisition channels, complaint types, and support burden through shared sidebar controls.</p>
</section>
</section>
<section id="proposed-ui-design" class="level1">
<h1>6 Proposed UI Design</h1>
<section id="proposed-inputs" class="level2">
<h2 class="anchored" data-anchor-id="proposed-inputs">6.1 Proposed Inputs</h2>
<p>The future Shiny module will expose the following input controls:</p>
<ul>
<li><code>customer_segment</code></li>
<li><code>acquisition_channel</code></li>
<li><code>feedback_sentiment</code></li>
<li><code>complaint_topics</code></li>
<li><code>product ownership</code></li>
<li><code>support_ticket_bucket</code></li>
<li><code>feature_usage_bucket</code></li>
</ul>
<p>These parameters allow users to investigate whether customer engagement, service experience, and friction vary across different customer subgroups.</p>
</section>
<section id="proposed-outputs" class="level2">
<h2 class="anchored" data-anchor-id="proposed-outputs">6.2 Proposed Outputs</h2>
<p>The module will display the following analytical outputs:</p>
<ul>
<li>average feature usage diversity by product ownership</li>
<li>average app login frequency by product ownership</li>
<li>NPS score by satisfaction score</li>
<li>NPS score by feature usage diversity bucket</li>
<li>complaint topics distribution</li>
<li>NPS score by support ticket bucket</li>
<li>KPI summary cards</li>
<li>product-level engagement summary table</li>
<li>product-level login summary table</li>
</ul>
<p>Together, these outputs help users understand how customers use the platform, how interaction connects to service experience, and where operational friction may influence customer advocacy.</p>
</section>
<section id="proposed-ui-components-and-layout" class="level2">
<h2 class="anchored" data-anchor-id="proposed-ui-components-and-layout">6.3 Proposed UI Components and Layout</h2>
<p>The proposed Shiny UI follows a sidebar–main panel layout.</p>
<p><strong>Sidebar filters</strong> - <code>selectInput()</code> for customer segment - <code>selectInput()</code> for acquisition channel - <code>selectInput()</code> for feedback sentiment - <code>selectInput()</code> for complaint topics - <code>checkboxGroupInput()</code> for product ownership - <code>selectInput()</code> for support ticket bucket - <code>selectInput()</code> for feature usage bucket</p>
<p><strong>Main panel</strong> - Top section: KPI cards for average satisfaction, average NPS, average support tickets, and average feature usage diversity - Middle section: product-related engagement views and experience evaluation views, including feature usage diversity, login frequency, and NPS by satisfaction - Bottom section: diagnostic views for interaction–advocacy linkage and service friction, including NPS by feature usage bucket, complaint composition, and NPS by support ticket bucket</p>
<p>This layout supports interactive exploration of customer engagement, customer advocacy, and service friction, while maintaining logical continuity with Module 1 and Module 3.</p>
</section>
<section id="early-ui-storyboard-sketch" class="level2">
<h2 class="anchored" data-anchor-id="early-ui-storyboard-sketch">6.4 Early UI Storyboard Sketch</h2>
<p>The figure below shows an early storyboard sketch for Module 2. It was used during the initial design stage to think through the overall sidebar–main panel layout, including the placement of filters and the arrangement of engagement and experience views.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="data/module2_sketch.jpg" class="img-fluid figure-img"></p>
<figcaption>Early UI storyboard sketch for Module 2</figcaption>
</figure>
</div>
<p>Although the specific charts in the final prototype were later refined based on the actual data patterns, this sketch remained useful as an initial reference for the module layout. In particular, it supported the decision to organise the module into a filter sidebar, a set of summary indicators at the top, and multiple diagnostic visual views in the main panel.</p>
</section>
</section>
<section id="prototype-visualisations" class="level1">
<h1>7 Prototype Visualisations</h1>
<section id="average-feature-usage-diversity-by-product-ownership-1" class="level2">
<h2 class="anchored" data-anchor-id="average-feature-usage-diversity-by-product-ownership-1">7.1 Average Feature Usage Diversity by Product Ownership</h2>
<p>The code chunk below is used to compare average feature usage diversity across product ownership groups.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>product_engagement_summary <span class="ot">&lt;-</span> customer_m2 <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    feature_usage_diversity,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    savings_account,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    credit_card,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    personal_loan,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    investment_account,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    insurance_product</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">c</span>(</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>      savings_account,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>      credit_card,</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>      personal_loan,</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>      investment_account,</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>      insurance_product</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"product_type"</span>,</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"owned"</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">product_type =</span> <span class="fu">recode</span>(</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>      product_type,</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>      <span class="at">savings_account =</span> <span class="st">"Savings Account"</span>,</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>      <span class="at">credit_card =</span> <span class="st">"Credit Card"</span>,</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>      <span class="at">personal_loan =</span> <span class="st">"Personal Loan"</span>,</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">investment_account =</span> <span class="st">"Investment Account"</span>,</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>      <span class="at">insurance_product =</span> <span class="st">"Insurance Product"</span></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">ownership_status =</span> <span class="fu">if_else</span>(owned, <span class="st">"Own"</span>, <span class="st">"Not Own"</span>)</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(product_type, ownership_status) <span class="sc">%&gt;%</span></span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_feature_diversity =</span> <span class="fu">mean</span>(feature_usage_diversity, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb20-39"><a href="#cb20-39" aria-hidden="true" tabindex="-1"></a>  product_engagement_summary,</span>
<span id="cb20-40"><a href="#cb20-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb20-41"><a href="#cb20-41" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> product_type,</span>
<span id="cb20-42"><a href="#cb20-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> avg_feature_diversity,</span>
<span id="cb20-43"><a href="#cb20-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> ownership_status</span>
<span id="cb20-44"><a href="#cb20-44" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-45"><a href="#cb20-45" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb20-46"><a href="#cb20-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb20-47"><a href="#cb20-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb20-48"><a href="#cb20-48" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Average Feature Usage Diversity by Product Ownership"</span>,</span>
<span id="cb20-49"><a href="#cb20-49" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Product Type"</span>,</span>
<span id="cb20-50"><a href="#cb20-50" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Average Feature Usage Diversity"</span>,</span>
<span id="cb20-51"><a href="#cb20-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Ownership Status"</span></span>
<span id="cb20-52"><a href="#cb20-52" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb20-53"><a href="#cb20-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb20-54"><a href="#cb20-54" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">20</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span>
<span id="cb20-55"><a href="#cb20-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-56"><a href="#cb20-56" aria-hidden="true" tabindex="-1"></a>p1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This visualisation shows that product ownership is strongly associated with broader platform usage. Across all five product types, customers who own the product consistently exhibit higher average feature usage diversity than those who do not. The largest differences appear for savings accounts, credit cards, investment accounts, and personal loans. This suggests that product adoption is not only a structural characteristic of the customer base, but also an important behavioural signal of deeper platform engagement.</p>
</section>
<section id="average-app-login-frequency-by-product-ownership-1" class="level2">
<h2 class="anchored" data-anchor-id="average-app-login-frequency-by-product-ownership-1">7.2 Average App Login Frequency by Product Ownership</h2>
<p>The code chunk below is used to compare average app login frequency across product ownership groups.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>product_login_summary <span class="ot">&lt;-</span> customer_m2 <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    app_logins_frequency,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    savings_account,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    credit_card,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    personal_loan,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    investment_account,</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    insurance_product</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">c</span>(</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>      savings_account,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>      credit_card,</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>      personal_loan,</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>      investment_account,</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>      insurance_product</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"product_type"</span>,</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"owned"</span></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">product_type =</span> <span class="fu">recode</span>(</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>      product_type,</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>      <span class="at">savings_account =</span> <span class="st">"Savings Account"</span>,</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>      <span class="at">credit_card =</span> <span class="st">"Credit Card"</span>,</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>      <span class="at">personal_loan =</span> <span class="st">"Personal Loan"</span>,</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">investment_account =</span> <span class="st">"Investment Account"</span>,</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>      <span class="at">insurance_product =</span> <span class="st">"Insurance Product"</span></span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">ownership_status =</span> <span class="fu">if_else</span>(owned, <span class="st">"Own"</span>, <span class="st">"Not Own"</span>)</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(product_type, ownership_status) <span class="sc">%&gt;%</span></span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_logins =</span> <span class="fu">mean</span>(app_logins_frequency, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a>  product_login_summary,</span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb21-41"><a href="#cb21-41" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> product_type,</span>
<span id="cb21-42"><a href="#cb21-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> avg_logins,</span>
<span id="cb21-43"><a href="#cb21-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> ownership_status</span>
<span id="cb21-44"><a href="#cb21-44" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb21-45"><a href="#cb21-45" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb21-46"><a href="#cb21-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb21-47"><a href="#cb21-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-48"><a href="#cb21-48" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Average App Login Frequency by Product Ownership"</span>,</span>
<span id="cb21-49"><a href="#cb21-49" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Product Type"</span>,</span>
<span id="cb21-50"><a href="#cb21-50" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Average App Login Frequency"</span>,</span>
<span id="cb21-51"><a href="#cb21-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Ownership Status"</span></span>
<span id="cb21-52"><a href="#cb21-52" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-53"><a href="#cb21-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb21-54"><a href="#cb21-54" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">20</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span>
<span id="cb21-55"><a href="#cb21-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-56"><a href="#cb21-56" aria-hidden="true" tabindex="-1"></a>p2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This visualisation extends the engagement analysis from usage breadth to usage intensity. However, unlike feature usage diversity, average app login frequency appears almost identical between product owners and non-owners across all product categories. This suggests that login frequency is not a strong differentiator of customer engagement in the current dataset, and that breadth of feature use may be more informative than simple access frequency.</p>
</section>
<section id="nps-score-by-satisfaction-score-1" class="level2">
<h2 class="anchored" data-anchor-id="nps-score-by-satisfaction-score-1">7.3 NPS Score by Satisfaction Score</h2>
<p>The code chunk below is used to compare NPS score distributions across satisfaction score levels.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  customer_m2 <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">satisfaction_score =</span> <span class="fu">factor</span>(satisfaction_score)),</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> satisfaction_score,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> nps_score,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> satisfaction_score</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.8</span>, <span class="at">outlier.alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"NPS Score by Satisfaction Score"</span>,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Satisfaction Score"</span>,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"NPS Score"</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>p3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This visualisation shows a strong positive relationship between customer satisfaction and NPS. As satisfaction scores increase from 2 to 6, the distribution of NPS shifts upward substantially, moving from strongly negative values toward neutral or positive levels. This indicates that customer satisfaction is closely linked to customer advocacy in the current dataset and provides one of the clearest evaluations of service experience in this module.</p>
</section>
<section id="nps-score-by-feature-usage-diversity-bucket-1" class="level2">
<h2 class="anchored" data-anchor-id="nps-score-by-feature-usage-diversity-bucket-1">7.4 NPS Score by Feature Usage Diversity Bucket</h2>
<p>The code chunk below is used to compare NPS score distributions across grouped feature usage levels.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  customer_m2,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> feature_usage_bucket,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> nps_score,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> feature_usage_bucket</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.8</span>, <span class="at">outlier.alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"NPS Score by Feature Usage Diversity Bucket"</span>,</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Feature Usage Diversity Bucket"</span>,</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"NPS Score"</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>p4</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This visualisation connects platform interaction with customer advocacy by comparing NPS across grouped levels of feature usage diversity. The distributions suggest a modest upward tendency in NPS as feature usage breadth increases, but the separation across groups is not strong. This indicates that broader feature usage may be associated with slightly stronger advocacy, although it is not as powerful a driver as satisfaction itself.</p>
</section>
<section id="complaint-topics-distribution-excluding-none" class="level2">
<h2 class="anchored" data-anchor-id="complaint-topics-distribution-excluding-none">7.5 Complaint Topics Distribution (Excluding “None”)</h2>
<p>The code chunk below is used to visualise complaint topic frequencies among customers with recorded complaints only.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>complaint_summary_actual <span class="ot">&lt;-</span> customer_m2 <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(complaint_topics <span class="sc">!=</span> <span class="st">"None"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(complaint_topics, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>p5 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  complaint_summary_actual,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">fct_reorder</span>(complaint_topics, n),</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> n</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Complaint Topics Distribution (Excluding 'None')"</span>,</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Complaint Topic"</span>,</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of Customers"</span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>p5</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In the data preparation process, missing complaint records were recoded as “None”. To understand the actual composition of service issues, this visualisation focuses only on customers with recorded complaints. The results show that complaint frequencies are relatively evenly distributed across customer service, fees, transaction issues, account security, and app performance. This suggests that service friction is spread across multiple dimensions of the platform rather than concentrated in one dominant issue category.</p>
</section>
<section id="nps-score-by-support-ticket-bucket-1" class="level2">
<h2 class="anchored" data-anchor-id="nps-score-by-support-ticket-bucket-1">7.6 NPS Score by Support Ticket Bucket</h2>
<p>The code chunk below is used to compare NPS score distributions across grouped support ticket levels.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>p6 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  customer_m2,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> support_ticket_bucket,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> nps_score,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> support_ticket_bucket</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.8</span>, <span class="at">outlier.alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"NPS Score by Support Ticket Bucket"</span>,</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Support Ticket Bucket"</span>,</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"NPS Score"</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>p6</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This visualisation examines whether heavier support burden is associated with weaker customer advocacy. The NPS distributions remain broadly similar across grouped support ticket levels, with only a modest tendency toward weaker advocacy among customers with higher support burden. This suggests that support needs may reflect some degree of service friction, but they are not the strongest driver of customer advocacy in the current dataset.</p>
</section>
<section id="prototype-kpi-summary" class="level2">
<h2 class="anchored" data-anchor-id="prototype-kpi-summary">7.7 Prototype KPI Summary</h2>
<p>The code chunk below is used to compute summary indicators for the module.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>kpi_summary <span class="ot">&lt;-</span> customer_m2 <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_satisfaction =</span> <span class="fu">mean</span>(satisfaction_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_nps =</span> <span class="fu">mean</span>(nps_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_support_tickets =</span> <span class="fu">mean</span>(support_tickets_count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_feature_diversity =</span> <span class="fu">mean</span>(feature_usage_diversity, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>kpi_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  avg_satisfaction avg_nps avg_support_tickets avg_feature_diversity
             &lt;dbl&gt;   &lt;dbl&gt;               &lt;dbl&gt;                 &lt;dbl&gt;
1             4.16   -26.8               0.997                  2.37</code></pre>
</div>
</div>
<p>The KPI summary provides an overall view of engagement and service experience in the platform. Average satisfaction is 4.16, indicating a generally moderate-to-positive experience. However, average NPS is -26.8, suggesting that customers are not strong promoters despite relatively acceptable satisfaction levels. Average support ticket volume is approximately 1 per customer, while average feature usage diversity is only 2.37, implying that most customers use a limited number of platform functions.</p>
</section>
<section id="product-level-engagement-summary" class="level2">
<h2 class="anchored" data-anchor-id="product-level-engagement-summary">7.8 Product-level Engagement Summary</h2>
<p>The code chunk below is used to summarise feature usage diversity by product ownership.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>product_engagement_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   product_type       ownership_status avg_feature_diversity
   &lt;chr&gt;              &lt;chr&gt;                            &lt;dbl&gt;
 1 Credit Card        Not Own                           1.50
 2 Credit Card        Own                               2.89
 3 Insurance Product  Not Own                           2.12
 4 Insurance Product  Own                               3.31
 5 Investment Account Not Own                           1.81
 6 Investment Account Own                               3.12
 7 Personal Loan      Not Own                           1.97
 8 Personal Loan      Own                               3.23
 9 Savings Account    Not Own                           1.18
10 Savings Account    Own                               2.69</code></pre>
</div>
</div>
<p>This table reinforces the main finding from the engagement chart by quantifying the difference in feature usage diversity between product owners and non-owners. For every product category, customers who own the product show substantially higher average feature usage diversity. This confirms that product ownership is closely associated with deeper platform interaction and provides a useful bridge from Module 1 product adoption patterns to Module 2 engagement behaviour analysis.</p>
</section>
<section id="product-level-login-summary" class="level2">
<h2 class="anchored" data-anchor-id="product-level-login-summary">7.9 Product-level Login Summary</h2>
<p>The code chunk below is used to summarise app login frequency by product ownership.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>product_login_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   product_type       ownership_status avg_logins
   &lt;chr&gt;              &lt;chr&gt;                 &lt;dbl&gt;
 1 Credit Card        Not Own                22.5
 2 Credit Card        Own                    22.3
 3 Insurance Product  Not Own                22.4
 4 Insurance Product  Own                    22.4
 5 Investment Account Not Own                22.4
 6 Investment Account Own                    22.3
 7 Personal Loan      Not Own                22.4
 8 Personal Loan      Own                    22.4
 9 Savings Account    Not Own                22.3
10 Savings Account    Own                    22.4</code></pre>
</div>
</div>
<p>This table supports the interpretation of application usage intensity by showing that average login frequency is nearly identical across product ownership conditions. Unlike feature usage diversity, app login frequency does not appear to vary meaningfully between product owners and non-owners. This suggests that login frequency is a relatively weak indicator of differentiated customer engagement in the current dataset.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>8 Conclusion</h1>
<p>This prototype demonstrates how Module 2 of the proposed visual analytics dashboard can be used to examine customer engagement and service experience in a more complete and diagnostic way.</p>
<p>The analysis reveals four main findings. First, product ownership is strongly associated with broader platform usage. Customers who own financial products consistently use a wider range of platform features than those who do not, indicating that product adoption is closely linked to deeper engagement behaviour. Second, customer satisfaction is strongly associated with customer advocacy. As satisfaction scores increase, NPS shifts upward substantially, showing that service experience quality is closely connected to willingness to recommend the platform. Third, service friction is distributed across multiple complaint categories rather than concentrated in one dominant issue type. Fourth, the prototype also shows that not all engagement indicators are equally informative: feature usage breadth is more useful than app login frequency, while both support burden and feature usage breadth show only modest relationships with NPS compared with the much stronger effect of satisfaction.</p>
<p>Taken together, these findings position Module 2 as the behavioural and experience bridge between customer structure and downstream customer value analysis. The module shows that product adoption helps explain interaction breadth, that satisfaction is a key driver of advocacy, and that service friction emerges across multiple operational areas. At the same time, the prototype also reveals that some commonly assumed engagement indicators, such as login frequency, are less informative than broader feature usage. As part of the full Shiny application, this module can help fintech product and CRM teams better understand which behavioural and experience factors are most relevant before moving into retention risk and customer value analysis in Module 3.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>